// <auto-generated />
using System;
using EmlakProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmlakProject.DAL.Migrations
{
    [DbContext(typeof(EmlakContext))]
    [Migration("20210913124322_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmlakProject.Entities.EmlakBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BinaKati")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmlakTuru")
                        .HasColumnType("int");

                    b.Property<int>("EmlakciId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kat")
                        .HasColumnType("int");

                    b.Property<decimal>("MetreKare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmlakciId");

                    b.ToTable("EmlakBilgisi");
                });

            modelBuilder.Entity("EmlakProject.Entities.Emlakci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmlakciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fax")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emlakci");
                });

            modelBuilder.Entity("EmlakProject.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmlakciId")
                        .HasColumnType("int");

                    b.Property<string>("EvTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmlakciId");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("EmlakProject.Entities.EmlakBilgisi", b =>
                {
                    b.HasOne("EmlakProject.Entities.Emlakci", "Emlakci")
                        .WithMany("EmlakBilgisis")
                        .HasForeignKey("EmlakciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emlakci");
                });

            modelBuilder.Entity("EmlakProject.Entities.Musteri", b =>
                {
                    b.HasOne("EmlakProject.Entities.Emlakci", "Emlakci")
                        .WithMany("Musteris")
                        .HasForeignKey("EmlakciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emlakci");
                });

            modelBuilder.Entity("EmlakProject.Entities.Emlakci", b =>
                {
                    b.Navigation("EmlakBilgisis");

                    b.Navigation("Musteris");
                });
#pragma warning restore 612, 618
        }
    }
}
